name: swifttasker
description: A new Flutter project for SwiftTasker.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Using a recent Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Recommended for new projects

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
