// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// This file is generated automatically by the FlutterFire CLI.
// Please do not modify it manually.

// Note from Jules: This is a placeholder structure based on ChatGPT's guide.
// The actual firebase_options.dart is usually generated by `flutterfire configure`.
// If that command is run, it might produce a file with a slightly different structure
// or more platform-specific options. For now, this matches the guide's snippet.
// CRITICAL: REPLACE PLACEHOLDER VALUES WITH YOUR ACTUAL FIREBASE PROJECT CONFIG.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Web specific options - if you support web
      // return web; // Assuming 'web' is a FirebaseOptions instance defined below
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // return ios; // Assuming 'ios' is a FirebaseOptions instance
        throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for ios - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
      case TargetPlatform.macOS:
        // return macos; // Assuming 'macos' is a FirebaseOptions instance
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        // return windows; // Assuming 'windows' is a FirebaseOptions instance
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android specific options
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // Replace with your Android API Key
    appId: 'YOUR_ANDROID_APP_ID', // Replace with your Android App ID (e.g., 1:xxxx:android:xxxx)
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Replace with your Messaging Sender ID
    projectId: 'YOUR_PROJECT_ID', // Replace with your Project ID
    storageBucket: 'YOUR_STORAGE_BUCKET', // Replace with your Storage Bucket (e.g., project-id.appspot.com)
  );

  // Example for iOS (if needed, replace with actual values)
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'YOUR_IOS_API_KEY',
  //   appId: 'YOUR_IOS_APP_ID',
  //   messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  //   projectId: 'YOUR_PROJECT_ID',
  //   storageBucket: 'YOUR_STORAGE_BUCKET',
  //   iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  // );

  // Example for Web (if needed, replace with actual values)
  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'YOUR_WEB_API_KEY',
  //   appId: 'YOUR_WEB_APP_ID',
  //   messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  //   projectId: 'YOUR_PROJECT_ID',
  //   authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  //   storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  // );

  // Add other platforms like macOS, windows if needed
}
